### ISSUE TITLE
ApplicationVersionTest#testRouteConfig failures

### ISSUE THREAD

**Issue by anwar6953** [caskdata/cdap-integration-tests#826]
`ApplicationVersionTest#testRouteConfig` has been failing occasionally. I've not seen it fail on regular Coopr clusters, but I've seen it fail rather often on CM + Ambari clusters (even ambari clusters w/o HA enabled).
Attempting to rerun the test case against the same cluster from my local machine has resulted in the test passing.

If I stop Router on the cluster, and then restart it, then the test case has a much higher chance of failing. Because of that, I suspect the failure is related to https://issues.cask.co/browse/CDAP-5806

```
java.lang.AssertionError: All traffic should be routed to service v1 but service v2 is also reached.
	at org.junit.Assert.fail(Assert.java:88)
	at co.cask.cdap.apps.ApplicationVersionTest.testRouteConfig(ApplicationVersionTest.java:214)
```

**Comment by CuriousVini** [comment]
Removed this test in this PR https://github.com/caskdata/cdap-integration-tests/pull/949
